services:
  devcontainer:
    container_name: frigate-devcontainer
    # Forzamos el arranque del motor de Python directamente para evitar el "Fake Service"
    command: python3 -m frigate
    group_add:
      - "109" # render
      - "110" # render
      - "44"  # video
      - "46"  # plugdev
    shm_size: "256mb"
    build:
      context: .
      dockerfile: docker/main/Dockerfile
      target: devcontainer
    environment:
      YOLO_MODELS: ""
    ports:
      - "5000:5000"       # Interfaz Estándar (HTTP)
      - "8971:8971"       # Interfaz con Autenticación (HTTPS)
      - "8554:8554"       # RTSP feeds
      - "8555:8555/tcp"   # WebRTC
      - "8555:8555/udp"   # WebRTC
    volumes:
      - .:/opt/frigate:cached
      - .:/workspace/frigate:cached
      - ./web/dist:/opt/frigate/web:cached
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./debug:/media/frigate
    # Reiniciar siempre a menos que se detenga manualmente
    restart: unless-stopped

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - "1883:1883"
    restart: unless-stopped