services:
  devcontainer:
    container_name: securevu-devcontainer
    group_add:
      - "109"
      - "110"
      - "44"
      - "46"
    shm_size: "256mb"
    build:
      context: .
      dockerfile: docker/main/Dockerfile
      target: devcontainer
    environment:
      YOLO_MODELS: ""
    volumes:
      - .:/workspace/securevu:cached
      - ./web/dist:/opt/securevu/web:cached
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./debug:/media/securevu
    ports:
      - "5000:5000"
      - "8971:8971"
      - "8554:8554"
      - "8555:8555"
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - "1883:1883"

